export const pubKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCvkPXRAvuoayMmQ2iygbHIhE3L
MKUD0cJ/tpGtwPpNPRwJUaKskZXyDGRWekn3AgXY69wn6Dm+8Bs9JIEnD6i/0JD/
0kD8079/K3b/VpAwmQHkgAZ3qQDCl25Pf6JyDOlNoc/mUwKFcTqksQO11i9vq7Qp
EtqmFkxjKjrJI6ueMwIDAQAB
-----END PUBLIC KEY-----`